### PR TITLE
Verify yarn.lock is up to date

### PR DESCRIPTION
**Pull request by jonahgraham**

### CODE REVIEW

**Comment by jonahgraham** [comment]
This is to prevent the error that required #282 from being required in the future.

**Comment by jonahgraham** [comment]
@AdhamRagabMCHP - this new check will make sure I don't accidentally merge without an update yarn.lock in the future.

**Comment by AdhamRagabMCHP** [comment]
Sounds good - sorry about that! Some of the dependencies just looked like duplicates, but I'll be careful in the future!

**Comment by jonahgraham** [comment]
No worries - the dependency structures of yarn are very complex so it was a reasonable assumption you made.

**Pull request merged**
