### PR TITLE
send interrupt if running and in async mode

### PR DESCRIPTION
**Pull request by parisa-mchp**
Hi @jonahgraham,

Last week was @AdhamRagabMCHP's last week here. Although I don't know the ins and outs as well as he did, I'll be taking over the work he was doing on cdt-gdb-adapter. Without further ado, this commit makes the changes that were proposed in this PR: https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/287

### CODE REVIEW

**Comment by jonahgraham** [comment]
Hi @parisa-mchp - welcome!

Please [sign the ECA](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/main/CONTRIBUTING.md#eclipse-contributor-agreement) so that we can accept your patch. The patch looks fine and I look forward to merging it soon.

Once merged, you can let me know if you want me to make a new pre-release of it and the [vscode](https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode) extension too.

**Comment by parisa-mchp** [comment]
I've signed the ECA and fixed a minor formatting issue. Let me know if there's anything else you need before this can be merged.

**Comment by jonahgraham** [comment]
> fixed a minor formatting issue

Thanks for fixing that. I guess there are some git attributes missing on the repo that let windows newlines slip in there in the first place.

>  Let me know

The change LGTM and once build confirms there are no issues I can merge it. But just before I do I want to check that it is intentional that your name shows up like this in the git log:

image

**Comment by parisa-mchp** [comment]
I hadn't intended to do that, but that's my username on bitbucket, and it's totally fine that the commits show up like that.

**Comment by jonahgraham** [comment]
It is now merged. Please let me know if you want a new version published, or if you have other outstanding changes you want to submit first.

**Comment by jonahgraham** [comment]
> I hadn't intended to do that, but that's my username on bitbucket, and it's totally fine that the commits show up like that.

Because I ended up doing a squash and merge the main branch has the commit like this:

```
commit 143775c3d3b48e9e9ee91fc68814b3cf703e8155 (HEAD -> main, origin/main)
Author: parisa-mchp <127134562+parisa-mchp@users.noreply.github.com>
Date:   Thu Aug 31 15:16:06 2023 -0400

    Send interrupt before disconnecting from remote (#289)
```

**Comment by parisa-mchp** [comment]
> Please let me know if you want a new version published
If you could do this please that would be appreciated.

**Comment by jonahgraham** [comment]
I have published the new version to [npm](https://www.npmjs.com/package/cdt-gdb-adapter/v/0.0.27) but it looks like I need to resolve #288 and https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/pull/96 before I can publish the next cdt-gdb-vscode. I'll aim to work with @colin-grant-work to get this done ASAP.

**Comment by jonahgraham** [comment]
Thanks @parisa-mchp for this fix.

The vscode part has now been updated with this change (see https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/releases/tag/v0.0.102) - overnight tonight the 0.0.102 version should be automatically published to [openvsx](https://open-vsx.org/extension/eclipse-cdt/cdt-gdb-vscode). Please raise an issue (like https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/issues/95) if it doesn't end up there as it seems there has been some instability on the auto-publish.

**Pull request merged**
