### PR TITLE
Add attach test

### PR DESCRIPTION
**Pull request by simark**
Add some simple "attach" tests, one when we successfully attach and one
when we provide a non-existent pid.

I kept it really simple, because I don't yet know what is the right
behavior we should test for.  For example, if the client sends a
configurationDone after a failed attach request, what should we reply?
So the tests can be improved at a later point.

I started to move things out of the existing test to a shared library of
test utilities.

Signed-off-by: Simon Marchi <simon.marchi@ericsson.com>

### CODE REVIEW

**Comment by simark** [comment]
We'll need to investigate why it fails on Jenkins... it looks like the debug client doesn't get any reponse at all for the attach request.

**Comment by simark** [comment]
It would be a good opportunity to improve how we do logging and make it available after a Jenkins run :)

**Comment by dschaefer** [comment]
In theory, you could also run in verbose mode and add a listener to LogOutputEvents to see what gdb is doing.

**Comment by simark** [comment]
I have the intuition that #38 will help... let's see.

**Comment by jonahgraham** [comment]
Sorry, this is the PR that hung the build: https://ci.eclipse.org/cdt/job/cdt-gdb-adapter-verify/41/console

I am cancelling it and putting a timelimit on the build time.

**Comment by dschaefer** [comment]
Now that logging is working, we should generate and archive the log.

**Comment by dschaefer** [comment]
Just ran into something similar. It looks like attach was missing the sendFileExecAndSymbols call. I fixed that in my latest update. And, yes, I did see that in the new log file :).

Suggest rebasing and trying again.

**Comment by jonahgraham** [comment]
Please recreate this PR against the "main" branch. Ref: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/793#note_571779

**Pull request closed without merging**
